name: 'Netrc Creds'
description: 'Sets up netrc credentials. Useful for setting up a PAT for git to use in an action.'
branding:
  icon: lock
  color: yellow
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  creds:
    description: 'JSON array of object with (`machine`, `login`, `password`) fields.'
    required: false
  machine:
    description: 'machine string to append'
    required: false
  login:
    description: 'login field to append'
    required: false
  password:
    description: password field to append
    required: false
